### ISSUE TITLE
yml文件里配置了use scanner 为true 不加@service的handler没有自动扫描加入到bootstrap中

### ISSUE THREAD

**Issue by c834292137** [fanpan26/tio-starters#2]
yml文件里配置了use scanner 为true 不加@service的handler没有自动扫描加入到bootstrap中

**Comment by fanpan26** [comment]
@c834292137  OK ，抽空看一下。

**Comment by fanpan26** [comment]
@c834292137 你好，问题能否具体一些，我测试了 tio-websocket-starter ，扫描是起作用的。

**Comment by yichengxian** [comment]
这都2020年了这个问题还是没处理，帮忙维护一下社区

**Comment by fanpan26** [comment]
@yichengxian 处理了，只是忘记关掉了。多谢关注和提醒。
