### ISSUE TITLE
请问如何自定义WsServerAioListener或ServerAioListener？

### ISSUE THREAD

**Issue by dujianchi** [fanpan26/tio-starters#7]
请问如何自定义WsServerAioListener或ServerAioListener？
用的
        <dependency>
            <groupId>org.t-io</groupId>
            <artifactId>tio-websocket-spring-boot-starter</artifactId>
            <version>3.6.0.v20200315-RELEASE</version>
        </dependency>
自行配置监听，加了
@Component
@Service
@TioServerAioListener
都不行

**Comment by dujianchi** [comment]
3.5.9.v20200214-RELEASE  测试了一下，这个版本可以用，那就是最新版有bug

**Comment by dujianchi** [comment]
原来是要加 use-scanner: true

**Comment by fanpan26** [comment]
@dujianchi 好久没维护了，感谢使用，实在不行，自己照着源码鲁一个~
